#!/bin/bash

set -e

# Parse arguments
BUILD_ARCH=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --arch)
            BUILD_ARCH=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--arch]"
            exit 1
            ;;
    esac
done

VERSION="24.11.01"
BUILD_DIR="build"

if [ "$BUILD_ARCH" = true ]; then
    PKGNAME="system-keyboard-qt-${VERSION}.pkg.tar.zst"
    PKG_DIR="pkg"
    echo "Building Arch Linux package"
else
    echo "Building Debian package"
fi

if [ "$BUILD_ARCH" = true ]; then
    # Clean previous build
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"

    # Generate translations
    if command -v lrelease-qt6 &> /dev/null; then
        lrelease-qt6 ../translations/*.ts
    elif [ -x "/usr/lib/qt6/bin/lrelease" ]; then
        /usr/lib/qt6/bin/lrelease ../translations/*.ts
    elif command -v lrelease &> /dev/null; then
        lrelease ../translations/*.ts
    else
        echo "Warning: lrelease not found, skipping translation generation"
    fi

    # Configure with cmake
    cmake -GNinja .. -DCMAKE_INSTALL_PREFIX=/usr

    # Build
    ninja

    # Create package directory structure
    mkdir -p "$PKG_DIR/usr/bin"
    mkdir -p "$PKG_DIR/usr/share/applications"
    mkdir -p "$PKG_DIR/usr/share/icons/hicolor/scalable/apps"
    mkdir -p "$PKG_DIR/usr/share/system-keyboard-qt/locale"
    mkdir -p "$PKG_DIR/usr/share/doc/system-keyboard-qt/help"
    mkdir -p "$PKG_DIR/usr/share/polkit-1/actions"
    mkdir -p "$PKG_DIR/usr/lib/system-keyboard-qt"

    # Install built files
    DESTDIR="$PKG_DIR" ninja install

    # Copy additional files
    cp ../system-keyboard-qt.desktop "$PKG_DIR/usr/share/applications/"
    cp ../system-keyboard-qt.svg "$PKG_DIR/usr/share/icons/hicolor/scalable/apps/"
    cp ../translations/*.qm "$PKG_DIR/usr/share/system-keyboard-qt/locale/" 2>/dev/null || true
    cp -r ../help/* "$PKG_DIR/usr/share/doc/system-keyboard-qt/help/"
    cp ../policy/* "$PKG_DIR/usr/share/polkit-1/actions/"
    cp ../lib/* "$PKG_DIR/usr/lib/system-keyboard-qt/"

    # Compress and copy changelog for Arch Linux
    gzip -c ../debian/changelog > "$PKG_DIR/usr/share/doc/system-keyboard-qt/changelog.gz"

    # Create default X11 keyboard config for Arch Linux
    mkdir -p "$PKG_DIR/etc/X11/xorg.conf.d"
    cat > "$PKG_DIR/etc/X11/xorg.conf.d/00-keyboard.conf" << 'EOF'
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbModel" "pc105"
        Option "XkbLayout" "us"
        Option "XkbVariant" ""
        Option "XkbOptions" ""
EndSection
EOF

    # Create proper .PKGINFO
    cat > "$PKG_DIR/.PKGINFO" << 'EOF'
# Generated by build.sh
pkgname = system-keyboard-qt
pkgbase = system-keyboard-qt
xdata = pkgtype=pkg
pkgver = 24.11.01-1
pkgdesc = System keyboard configuration tool
url = https://github.com/mxlinux/system-keyboard-qt
builddate = 1735227896
packager = Unknown Packager
size = 770048
arch = x86_64
license = GPL
backup = etc/X11/xorg.conf.d/00-keyboard.conf
depend = qt6-base
optdepend = flags-common: Flag icons for keyboard layout selection
makedepend = cmake
makedepend = ninja
makedepend = qt6-tools
EOF

    # Create .BUILDINFO
    cat > "$PKG_DIR/.BUILDINFO" << 'EOF'
# Generated by build.sh
builddate = 1735227896
builddir = /home/adrian/Sync/programs/qt/system-keyboard-qt/build
buildenv = !distcc !color !ccache !check !debug !strip !lto
buildtool = cmake
buildtoolver = 3.31.0
editor = nano
maker = adrian
options = !strip !docs !libtool !staticlibs !emptydirs !zipman !purge !debug
packager = Unknown Packager
EOF

    # Create .MTREE
    cd "$PKG_DIR"
    mtree -c -p . > .MTREE 2>/dev/null || echo "# Basic MTREE" > .MTREE

    # Create the tar.zst package with metadata files first (remove ./ prefix)
    tar -cf - --transform 's|^\./||' .BUILDINFO .MTREE .PKGINFO $(find . -type f | grep -v '^\./\.BUILDINFO\|^\./\.MTREE\|^\./\.PKGINFO' | sort | sed 's|^\./||') | zstd -T0 -19 -o "../$PKGNAME"

    echo "Arch package created: $BUILD_DIR/$PKGNAME"
else
    # Build Debian package
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"

    # Generate translations
    if command -v lrelease-qt6 &> /dev/null; then
        lrelease-qt6 ../translations/*.ts
    elif [ -x "/usr/lib/qt6/bin/lrelease" ]; then
        /usr/lib/qt6/bin/lrelease ../translations/*.ts
    elif command -v lrelease &> /dev/null; then
        lrelease ../translations/*.ts
    else
        echo "Warning: lrelease not found, skipping translation generation"
    fi

    # Build Debian package using cmake+ninja
    cmake -GNinja .. -DCMAKE_INSTALL_PREFIX=/usr
    ninja

    # Create Debian package structure
    mkdir -p debian/system-keyboard-qt/usr/bin
    mkdir -p debian/system-keyboard-qt/usr/share/applications
    mkdir -p debian/system-keyboard-qt/usr/share/icons/hicolor/scalable/apps
    mkdir -p debian/system-keyboard-qt/usr/share/system-keyboard-qt/locale
    mkdir -p debian/system-keyboard-qt/usr/share/doc/system-keyboard-qt/help
    mkdir -p debian/system-keyboard-qt/usr/share/polkit-1/actions
    mkdir -p debian/system-keyboard-qt/usr/lib/system-keyboard-qt

    # Install files
    DESTDIR=debian/system-keyboard-qt ninja install

    # Copy additional files
    cp ../system-keyboard-qt.desktop debian/system-keyboard-qt/usr/share/applications/
    cp ../system-keyboard-qt.svg debian/system-keyboard-qt/usr/share/icons/hicolor/scalable/apps/
    cp ../translations/*.qm debian/system-keyboard-qt/usr/share/system-keyboard-qt/locale/ 2>/dev/null || true
    cp -r ../help/* debian/system-keyboard-qt/usr/share/doc/system-keyboard-qt/help/
    cp ../policy/* debian/system-keyboard-qt/usr/share/polkit-1/actions/
    cp ../lib/* debian/system-keyboard-qt/usr/lib/system-keyboard-qt/

    # Create .deb package
    dpkg-deb --build debian/system-keyboard-qt .

    echo "Debian package created: system-keyboard-qt.deb"
fi
